---
dependencies: []

galaxy_info:
  author: apolloclark
  description: Install and configure RetireJS as a Jenkins job
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - security
    - devsecops
    - jenkins
    - retirejs