# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: all
  connection: local
  gather_facts: yes
  become: true
  become_user: "root"
  vars_files:
    - "vars.yml"
  pre_tasks:
    - name: Configure for RHEL 8, ignore missing bison and readline-devl packages
      set_fact:
        rvm1_autolib_mode: read
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'
  roles:
    - rvm.ruby
  tasks:
    - include: tasks/gems.yml
